### ISSUE TITLE
An error happened when start up

### ISSUE THREAD

**Issue by sunxfancy** [zefie/multi-tts#1]
Hi zefie,
I meet an error today when using your docker. It raises the message: RuntimeError: cannot cache function '__shear_dense': no locator available.

My system is Windows11 with docker-desktop WSL2 enabled. Do you have any idea?

```
docker-compose up
[+] Running 3/1
 ✔ Network multi-tts_default             Created                                             0.1s 
 ✔ Volume "multi-tts_multitts-cache"     Created                                             0.0s 
 ✔ Container multi-tts-zefie-multitts-1  Created                                             0.1s 
Attaching to zefie-multitts-1
zefie-multitts-1  | Loading Numpy
zefie-multitts-1  | Loading GRadio
zefie-multitts-1  | Loading torch, torchaudio, and librosa...
zefie-multitts-1  | Traceback (most recent call last):
zefie-multitts-1  |   File "/home/app/gradio_app.py", line 6, in <module>
 7, in <module>
zefie-multitts-1  |     from . import notation
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/librosa/core/notation.py", line 8, in <module>
zefie-multitts-1  |     from ..util.exceptions import ParameterError
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/librosa/util/__init__.py", line 77, in <module>
zefie-multitts-1  |     from .utils import *  # pylint: disable=wildcard-import
zefie-multitts-1  |     ^^^^^^^^^^^^^^^^^^^^
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/librosa/util/utils.py", line 1878, in <module>
zefie-multitts-1  |     @numba.jit(nopython=True, cache=True)
zefie-multitts-1  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/numba/core/decorators.py", line 225, in wrapper
zefie-multitts-1  |     disp.enable_caching()
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/numba/core/dispatcher.py", line 808, in enable_caching
zefie-multitts-1  |     self._cache = FunctionCache(self.py_func)
zefie-multitts-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/numba/core/caching.py", line 601, in __init__
zefie-multitts-1  |     self._impl = self._impl_class(py_func)
zefie-multitts-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
zefie-multitts-1  |   File "/opt/conda/lib/python3.11/site-packages/numba/core/caching.py", line 337, in __init__
zefie-multitts-1  |     raise RuntimeError("cannot cache function %r: no locator available "
zefie-multitts-1  | RuntimeError: cannot cache function '__shear_dense': no locator available for file '/opt/conda/lib/python3.11/site-packages/librosa/util/utils.py'
zefie-multitts-1 exited with code 1
```

**Comment by zefie** [comment]
Apologies for the delay, I also use Win11 and WSL2, but haven not been able to reproduce this. Can you try running without docker-compose? I use the following command in a shell script usually (edit the paths as necessary):

```bash
#!/bin/bash
docker run --rm -it -v /home/zefie/dev/multi-tts/srcwav:/home/app/srcwav \
        -p 7860:7860 --gpus=all \
        -v "${HOME}/.cache:/home/app/.cache" \
        -v "${HOME}/stable-diffusion/models:/models" \
        zefie/multi-tts:latest
```

**Comment by sunxfancy** [comment]
Hi zefie,
Thanks for your suggestion. I am not sure if the `stable-diffusion/models` path are necessary? 
I run without it and get the same output:
```
 docker run --rm -it -v /mnt/h/Workspace/multi-tts/srcwav:/home/app/srcwav         -p 7860:7860 --gpus=all         -v "${HOME}/.cache:/home/app/.cache"         zefie/multi-tts:latest
Loading Numpy
Loading GRadio
Loading torch, torchaudio, and librosa...
Traceback (most recent call last):
  File "/home/app/gradio_app.py", line 6, in <module>
    import torch, torchaudio, librosa
  File "/opt/conda/lib/python3.11/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/opt/conda/lib/python3.11/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/opt/conda/lib/python3.11/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/conda/lib/python3.11/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/librosa/util/utils.py", line 1878, in <module>
    @numba.jit(nopython=True, cache=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/numba/core/decorators.py", line 225, in wrapper
    disp.enable_caching()
  File "/opt/conda/lib/python3.11/site-packages/numba/core/dispatcher.py", line 808, in enable_caching
    self._cache = FunctionCache(self.py_func)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/opt/conda/lib/python3.11/site-packages/librosa/util/utils.py'
```

It looks like the cache issue. Would you like to clean the cache and try it again?

**Comment by zefie** [comment]
The stable-diffusion/models path is where models will be stored, it can be anything you like, such as a docker volume.
As for the cache, I linked it to ${HOME}/.cache to speed things up for me when building, but perhaps it causes issues on other machines. Try assigning that to a volume as well:

```bash
#!/bin/bash
docker run --rm -it -v /home/zefie/dev/multi-tts/srcwav:/home/app/srcwav \
        -p 7860:7860 --gpus=all \
        -v "tts-cache:/home/app/.cache" \
        -v "tts-models:/models" \
        zefie/multi-tts:latest
```
